import { mutation } from "./_generated/server";

// Seed the 12 Kaltirsi months
export const seedMonths = mutation({
  args: {},
  handler: async (ctx) => {
    // Check if already seeded
    const existing = await ctx.db.query("kaltirsiMonths").first();
    if (existing) {
      return "Already seeded";
    }

    const months = [
      {
        monthNumber: 1,
        nameSomali: "Samalaho",
        nameEnglish: "First Month",
        meaning: "Beginning - New fires lit",
        meaningSomali: "Bilowga - Dabka cusub ayaa la shiidaa",
        season: "Xagaa",
        seasonEnglish: "Summer/Dry Heat",
        description: "First month of the Kaltirsi year, coinciding with July 20th (Dabshid)",
        descriptionSomali: "Bisha kowaad ee sannadka Kaltirsi, oo ku beegan Luuliyo 20 (Dabshid)",
        agriculturalActivities: ["Harvesting last Gu crops", "Storing grain"],
        culturalEvents: ["Dabshid fire festival", "New Year celebrations"],
        startStarGroup: 1,
        approximateGregorianStart: "July 20",
      },
      {
        monthNumber: 2,
        nameSomali: "Karan",
        nameEnglish: "Second Month",
        meaning: "Hot season continues",
        meaningSomali: "Xilliga kulaylku wuu sii socdo",
        season: "Xagaa",
        seasonEnglish: "Summer/Dry Heat",
        description: "Peak heat season, livestock moved to water sources",
        descriptionSomali: "Xilliga ugu kulul, xoolaha loo guuro biyaha",
        agriculturalActivities: ["Minimal farming", "Water conservation"],
        culturalEvents: ["Star watching gatherings"],
        startStarGroup: 3,
        approximateGregorianStart: "August 20",
      },
      {
        monthNumber: 3,
        nameSomali: "Diraac-good",
        nameEnglish: "Third Month",
        meaning: "Extended arm",
        meaningSomali: "Gacanta la fidisay",
        season: "Xagaa",
        seasonEnglish: "Summer/Dry Heat",
        description: "End of Xagaa, preparations for Dayr rains",
        descriptionSomali: "Dhamaadka Xagaa, diyaarinta roobka Dayr",
        agriculturalActivities: ["Preparing fields", "Seed selection"],
        culturalEvents: ["Pre-rain ceremonies"],
        startStarGroup: 5,
        approximateGregorianStart: "September 20",
      },
      {
        monthNumber: 4,
        nameSomali: "Dambasame",
        nameEnglish: "Fourth Month",
        meaning: "Camel star rises",
        meaningSomali: "Xiddigta geela ayaa soo baxda",
        season: "Dayr",
        seasonEnglish: "Short Rainy Season",
        description: "Dayr rains begin, named after the Dambasame star",
        descriptionSomali: "Roobka Dayr ayaa bilaabma, loo magac daray xiddigta Dambasame",
        agriculturalActivities: ["Planting begins", "Pastoral movement"],
        culturalEvents: ["Dambasame night observation on Oct 19"],
        startStarGroup: 7,
        approximateGregorianStart: "October 20",
      },
      {
        monthNumber: 5,
        nameSomali: "Xoomir",
        nameEnglish: "Fifth Month",
        meaning: "Abundance",
        meaningSomali: "Barwaaqo",
        season: "Dayr",
        seasonEnglish: "Short Rainy Season",
        description: "Main Dayr rains, pastoral abundance",
        descriptionSomali: "Roobka Dayr ee weyn, barwaaqada xoolaha",
        agriculturalActivities: ["Crop growth", "Livestock fattening"],
        culturalEvents: [],
        startStarGroup: 9,
        approximateGregorianStart: "November 20",
      },
      {
        monthNumber: 6,
        nameSomali: "Xays",
        nameEnglish: "Sixth Month",
        meaning: "Transition",
        meaningSomali: "Isbeddel",
        season: "Dayr",
        seasonEnglish: "Short Rainy Season",
        description: "End of Dayr, transition to dry season",
        descriptionSomali: "Dhamaadka Dayr, u beddel xilliga qalalan",
        agriculturalActivities: ["Harvesting Dayr crops"],
        culturalEvents: [],
        startStarGroup: 11,
        approximateGregorianStart: "December 20",
      },
      {
        monthNumber: 7,
        nameSomali: "Toddob",
        nameEnglish: "Seventh Month",
        meaning: "Seven",
        meaningSomali: "Toddoba",
        season: "Jiilaal",
        seasonEnglish: "Dry Cold Season",
        description: "Jiilaal begins, cool dry weather",
        descriptionSomali: "Jiilaal ayaa bilaabmaya, cimilo qabow oo qalalan",
        agriculturalActivities: ["Storage", "Livestock care"],
        culturalEvents: [],
        startStarGroup: 13,
        approximateGregorianStart: "January 20",
      },
      {
        monthNumber: 8,
        nameSomali: "Adhi-caseeye",
        nameEnglish: "Eighth Month",
        meaning: "Goat herding time",
        meaningSomali: "Waqtiga adhiga la daajiyo",
        season: "Jiilaal",
        seasonEnglish: "Dry Cold Season",
        description: "Peak Jiilaal, goats are herded carefully",
        descriptionSomali: "Jiilaalka ugu daran, adhiga si taxadar leh loo daajiyaa",
        agriculturalActivities: ["Fodder management"],
        culturalEvents: [],
        startStarGroup: 15,
        approximateGregorianStart: "February 20",
      },
      {
        monthNumber: 9,
        nameSomali: "Daydo",
        nameEnglish: "Ninth Month",
        meaning: "Waiting",
        meaningSomali: "Sugitaan",
        season: "Jiilaal",
        seasonEnglish: "Dry Cold Season",
        description: "End of Jiilaal, waiting for Gu rains",
        descriptionSomali: "Dhamaadka Jiilaal, sugitaanka roobka Gu",
        agriculturalActivities: ["Field preparation"],
        culturalEvents: ["Rain prayers"],
        startStarGroup: 17,
        approximateGregorianStart: "March 20",
      },
      {
        monthNumber: 10,
        nameSomali: "Seer-ma-weydo",
        nameEnglish: "Tenth Month",
        meaning: "Unbreakable bond",
        meaningSomali: "Xiriir aan kala go'ayn",
        season: "Gu'",
        seasonEnglish: "Main Rainy Season",
        description: "Gu rains begin, main growing season",
        descriptionSomali: "Roobka Gu ayaa bilaabma, xilliga beerashada ee weyn",
        agriculturalActivities: ["Main planting season", "Sorghum planting"],
        culturalEvents: ["Somaliland Independence Day (May 18)"],
        startStarGroup: 19,
        approximateGregorianStart: "April 20",
      },
      {
        monthNumber: 11,
        nameSomali: "Cawl",
        nameEnglish: "Eleventh Month",
        meaning: "Pasture grass",
        meaningSomali: "Cawska daaqsinta",
        season: "Gu'",
        seasonEnglish: "Main Rainy Season",
        description: "Peak Gu, lush pastures",
        descriptionSomali: "Guca ugu sarreeya, daaq badan",
        agriculturalActivities: ["Crop growth", "Livestock grazing"],
        culturalEvents: ["Republic Day (June 26)"],
        startStarGroup: 21,
        approximateGregorianStart: "May 20",
      },
      {
        monthNumber: 12,
        nameSomali: "Sagaal",
        nameEnglish: "Twelfth Month",
        meaning: "Nine (completion)",
        meaningSomali: "Sagaal (dhamaystir)",
        season: "Gu'",
        seasonEnglish: "Main Rainy Season",
        description: "End of Gu, preparing for new year",
        descriptionSomali: "Dhamaadka Gu, diyaarinta sanadka cusub",
        agriculturalActivities: ["Early harvesting", "New year preparations"],
        culturalEvents: ["Unity Day (July 1)", "Pre-Dabshid preparations"],
        startStarGroup: 23,
        approximateGregorianStart: "June 20",
      },
    ];

    for (const month of months) {
      await ctx.db.insert("kaltirsiMonths", month);
    }

    return `Seeded ${months.length} Kaltirsi months`;
  },
});

// Seed 13 major star seasons (simplified from 28 Goddad for MVP)
export const seedStarGroups = mutation({
  args: {},
  handler: async (ctx) => {
    // Check if already seeded
    const existing = await ctx.db.query("starGroups").first();
    if (existing) {
      return "Already seeded";
    }

    const starGroups = [
      {
        groupNumber: 1,
        nameSomali: "Asher",
        nameArabic: "الشعراء",
        nameEnglish: "Sirius",
        meaning: "The Bright One - New Year Star",
        meaningSomali: "Iftiinka - Xiddigta Sanadka Cusub",
        constellation: "Canis Major",
        mainStar: "Sirius (Alpha Canis Majoris)",
        daysInGroup: 14,
        monthAssociation: 1,
        weatherPattern: "Peak dry heat, minimal rain",
        weatherPatternSomali: "Kulaylka ugu badan, roob yar",
        agriculturalSignificance: "Post-harvest storage",
        agriculturalSignificanceSomali: "Kaydinta goosashada ka dib",
        proverb: "Asher soo baxday, dabka shid",
        proverbEnglish: "When Sirius rises, light the fire",
      },
      {
        groupNumber: 2,
        nameSomali: "Budh",
        nameArabic: "البُدح",
        nameEnglish: "Canopus",
        meaning: "The Guardian",
        meaningSomali: "Ilaaliyaha",
        constellation: "Carina",
        mainStar: "Canopus",
        daysInGroup: 14,
        monthAssociation: 1,
        weatherPattern: "Intense heat continues",
        weatherPatternSomali: "Kulaylka daran ayaa sii socdo",
        agriculturalSignificance: "Water source protection",
        agriculturalSignificanceSomali: "Ilaalinta biyaha",
      },
      {
        groupNumber: 3,
        nameSomali: "Dirir",
        nameArabic: "الدرير",
        nameEnglish: "Spica",
        meaning: "The Swift One",
        meaningSomali: "Kan degdegga ah",
        constellation: "Virgo",
        mainStar: "Spica (Alpha Virginis)",
        daysInGroup: 14,
        monthAssociation: 2,
        weatherPattern: "Heat begins to break",
        weatherPatternSomali: "Kulaylka wuu yaraanayaa",
        agriculturalSignificance: "Pre-rain preparation",
        agriculturalSignificanceSomali: "Diyaarinta roobka hortii",
        proverb: "Dirir cirka marto, roobku wuu soo dhowyahay",
        proverbEnglish: "When Dirir crosses the sky, rain approaches",
      },
      {
        groupNumber: 4,
        nameSomali: "Dambasame",
        nameArabic: "دمبسمي",
        nameEnglish: "Pleiades Rising",
        meaning: "The Camel Star",
        meaningSomali: "Xiddigta Geela",
        constellation: "Taurus",
        mainStar: "Pleiades (M45)",
        daysInGroup: 14,
        monthAssociation: 4,
        weatherPattern: "Dayr rains likely",
        weatherPatternSomali: "Roobka Dayr wuu dhacayaa",
        agriculturalSignificance: "Optimal planting time",
        agriculturalSignificanceSomali: "Waqtiga ugu fiican beerashada",
        proverb: "Dambasame cirka marto, geela waa la nuugsadaa",
        proverbEnglish: "When Dambasame crosses, camels are watered",
      },
      {
        groupNumber: 5,
        nameSomali: "Laxaha",
        nameArabic: "اللحاء",
        nameEnglish: "Pleiades Zenith",
        meaning: "The Herd",
        meaningSomali: "Adhiga",
        constellation: "Taurus",
        mainStar: "Pleiades cluster",
        daysInGroup: 14,
        monthAssociation: 5,
        weatherPattern: "Peak Dayr rains",
        weatherPatternSomali: "Roobka Dayr ee ugu badan",
        agriculturalSignificance: "Crops growing rapidly",
        agriculturalSignificanceSomali: "Beeraha dhaqso u koraya",
      },
    ];

    for (const star of starGroups) {
      await ctx.db.insert("starGroups", star);
    }

    return `Seeded ${starGroups.length} star groups`;
  },
});
